// <auto-generated />
namespace CodeFirstDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v6anotationschanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v6anotationschanges));
        
        string IMigrationMetadata.Id
        {
            get { return "202211090649055_v6-anotations changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
